
services:
  db:
    platform: linux/arm64
    image: postgres:16
    environment:
      POSTGRES_DB: real_estate
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d real_estate"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    platform: linux/arm64
    build: .
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: real_estate
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: securepassword
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: