version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust  # Temporary for development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser}"]
      interval: 5s
      timeout: 5s
      retries: 10  # Increased retries
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine  # Smaller image
    ports:
      - "6380:6379"
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      target: dev
    environment:
      - DJANGO_SETTINGS_MODULE=real_estate.settings.development
      - PYTHONPATH=/app
      - DEBUG=1
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: []


    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    stdin_open: true  # Keep container open
    tty: true         # Allocate pseudo-TTY

volumes:
  postgres_data:
  redis_data: