version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-real_estate}
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-securepassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser} -d ${POSTGRES_DB:-real_estate}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      target: dev  # Change to 'prod' for production
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=real_estate.settings.development
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB:-real_estate}
      - POSTGRES_USER=${POSTGRES_USER:-appuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-securepassword}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      target: dev
    command: celery -A real_estate worker --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=real_estate.settings.development
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data: