[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "real-estate"
version = "0.1.0"
description = "Real Estate Platform"
requires-python = ">=3.12"
dependencies = [
    "Django>=4.2",
    "psycopg2-binary>=2.9",
]