name: Docker Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'docker-compose.yml'
      - 'Dockerfile'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Oracle Cloud Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.OCI_REGISTRY }}
        username: ${{ secrets.OCI_USER }}
        password: ${{ secrets.OCI_TOKEN }}
    
    - name: Build and push
      run: |
        docker-compose -f docker-compose.yml -f compose/production.yml build
        docker-compose -f docker-compose.yml -f compose/production.yml push