name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: python:3.11-bullseye
      options: --user root

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - "5432:5432"

    steps:
    - uses: actions/checkout@v4

    - name: Verify structure
      run: |
        ls -la src/
        [ -d src/apps ] || { echo "Error: src/apps directory missing"; exit 1; }

    - name: Install system packages
      run: |
        apt-get update
        apt-get install -y build-essential libpq-dev

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install django psycopg2-binary pytest pytest-django pytest-cov
        pip install -r src/requirements/base.txt

    - name: Create test settings
      run: |
        mkdir -p src/core/
        cat << EOF > src/core/settings_test.py
        SECRET_KEY = 'test-key-123'
        INSTALLED_APPS = [
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'apps.listings',
        ]
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': '${{ env.POSTGRES_DB }}',
                'USER': '${{ env.POSTGRES_USER }}',
                'PASSWORD': '${{ env.POSTGRES_PASSWORD }}',
                'HOST': 'localhost',
                'PORT': '5432',
            }
        }
        EOF

    - name: Configure pytest
      run: |
        echo "[pytest]" > src/pytest.ini
        echo "testpaths = apps" >> src/pytest.ini
        echo "python_files = test_*.py" >> src/pytest.ini
        echo "DJANGO_SETTINGS_MODULE = core.settings_test" >> src/pytest.ini

    - name: Run tests
      env:
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_pass
        DJANGO_SETTINGS_MODULE: core.settings_test
        PYTHONPATH: /github/workspace/src
      run: |
        cd src
        python -c "import django; print(f'Django {django.__version__} installed')"
        python -c "from django.conf import settings; print('Apps:', settings.INSTALLED_APPS)"
        pytest apps/ --cov=apps --cov-report=xml -v

    - name: Upload coverage
      uses: codecov/codecov-action@v3