name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
      options: --user root

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - "5432:5432"

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y python3 python3-pip python3-dev libpq-dev

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements/dev.txt pytest pytest-cov
        
    - name: Run tests
      env:
        DATABASE_URL: postgres://test_user:test_pass@localhost:5432/test_db
      run: |
        cd src
        pytest --cov=. --cov-report=xml

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Upload coverage
      uses: codecov/codecov-action@v3