name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04  # Explicit container with sudo
      options: --user root  # Run as root to avoid sudo

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - "5432:5432"

    steps:
    - uses: actions/checkout@v4

    # GLIBC installation (simplified)
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y libc6 libc6-dev python3-dev libpq-dev

    - name: Set up Python 3.12  # Recommended stable version
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements/dev.txt pytest pytest-cov

    - name: Run tests
      env:
        DATABASE_URL: postgres://test_user:test_pass@localhost:5432/test_db
      run: |
        cd src
        pytest --cov=. --cov-report=xml

    - name: Upload coverage
      uses: codecov/codecov-action@v3