name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: python:3.11-bullseye  # Pre-loaded with Python 3.11
      options: --user root

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - "5432:5432"

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y build-essential libpq-dev nodejs npm

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements/dev.txt pytest pytest-cov

    - name: Run tests
      env:
        DATABASE_URL: postgres://test_user:test_pass@localhost:5432/test_db
      run: |
        cd src
        pytest --cov=. --cov-report=xml

    - name: Upload coverage
      uses: codecov/codecov-action@v3