name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        options: >-
          --add-host=host.docker.internal:host-gateway
        ports:
          - "5432:5432"
        # Add any other services your application needs here  
      
    steps:
    - uses: actions/checkout@v4        
    - name: Install GLIBC dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libc6 libc6-dev
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.13-dev"  # Will work when available
        allow-prereleases: true
        activate-environment: python_env
        environment-file: .github/actions/python-environment.yml
                
    - name: Install dependencies
      run: |
        pip install -r src/requirements/dev.txt
        pip install pytest pytest-django pytest-cov
        
    - name: Run tests
      env:
        DATABASE_URL: postgres://test_user:test_pass@localhost:5432/test_db
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        cd src
        pytest --cov=./ --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
    - name: Run tests
      run: |
        cd src
        pytest --collect-only -v  # Show what tests would run
        pytest --cov=. --cov-report=xml
    - name: Run tests
      run: |
        cd src
        pytest apps/listings/tests/ --cov=apps
      # ci.yml additions
    - name: Upload coverage
      uses: codecov/codecov-action@v3

permissions:
  contents: read
  packages: write  # For container registry pushes

  