name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: python:3.11-bullseye
      options: --user root

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - "5432:5432"

    steps:
    - uses: actions/checkout@v4

    - name: Verify project structure
      run: |
        ls -la src/
        [ -f src/core/__init__.py ] || touch src/core/__init__.py
        [ -f src/core/settings.py ] || django-admin startproject core src && mv src/core/settings.py src/core/original_settings.py

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y build-essential libpq-dev nodejs npm

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install django psycopg2-binary
        pip install -r src/apps/requirements/dev.txt
        pip install pytest pytest-cov pytest-django

    - name: Configure Django settings
      run: |
        echo "import os" > src/core/settings_test.py
        echo "from .settings import *" >> src/core/settings_test.py
        echo "DATABASES = {'default': {'ENGINE': 'django.db.backends.postgresql', 'NAME': os.getenv('POSTGRES_DB'), 'USER': os.getenv('POSTGRES_USER'), 'PASSWORD': os.getenv('POSTGRES_PASSWORD'), 'HOST': 'localhost', 'PORT': '5432'}}" >> src/core/settings_test.py

    - name: Configure pytest
      run: |
        echo "[pytest]" > src/pytest.ini
        echo "testpaths = apps" >> src/pytest.ini
        echo "python_files = test_*.py" >> src/pytest.ini
        echo "python_classes = *Test Test* *Tests" >> src/pytest.ini
        echo "DJANGO_SETTINGS_MODULE = core.settings_test" >> src/pytest.ini
        echo "addopts = --ds=core.settings_test" >> src/pytest.ini
        echo "pythonpath = src" >> src/pytest.ini

    - name: Run tests
      env:
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_pass
        DJANGO_SETTINGS_MODULE: core.settings_test
        PYTHONPATH: /github/workspace/src:/github/workspace
      run: |
        cd src
        python -c "import sys; print(sys.path)"
        python -c "from django.conf import settings; print('DATABASES:', settings.DATABASES)"
        pytest --cov=apps --cov-report=xml -v

    - name: Upload coverage
      uses: codecov/codecov-action@v3