name: Nightly Tests

on:
  schedule:
    - cron: '0 3 * * *'  # 3 AM daily

jobs:
  extended-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker-compose -f docker-compose.yml -f compose/test.yml up \
            --abort-on-container-exit \
            --exit-code-from web